"""Hand-curated fixture sites used by the API and the subset ingestion pipeline."""

from backend.engine.contracts import SiteFeature

FEATURE_COLLECTION: list[SiteFeature] = [
    SiteFeature(
        cell_id="851f25d7fffffff",
        country_code="SE",
        region_name="Lulea / Boden",
        latitude=65.5848,
        longitude=22.1547,
        mean_price_eur_mwh=34,
        price_volatility=17,
        carbon_intensity_g_kwh=24,
        congestion_index=0.22,
        headroom_mw=540,
        dist_hv_substation_km=7.2,
        dist_fiber_km=18.4,
        dist_ixp_km=710,
        latency_proxy_ms=14.8,
        solar_cf=0.10,
        wind_cf=0.42,
        water_dist_km=3.4,
        cooling_degree_proxy=0.18,
        buildable_fraction=0.72,
        dc_similarity=0.81,
        lightgbm_score=0.79,
        shap_values={"headroom_mw": 0.22, "carbon_intensity_g_kwh": 0.18, "wind_cf": 0.14},
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="851f2533fffffff",
        country_code="SE",
        region_name="Sundsvall",
        latitude=62.3908,
        longitude=17.3069,
        mean_price_eur_mwh=38,
        price_volatility=19,
        carbon_intensity_g_kwh=28,
        congestion_index=0.27,
        headroom_mw=390,
        dist_hv_substation_km=9.1,
        dist_fiber_km=12.0,
        dist_ixp_km=390,
        latency_proxy_ms=10.9,
        solar_cf=0.11,
        wind_cf=0.39,
        water_dist_km=2.8,
        cooling_degree_proxy=0.24,
        buildable_fraction=0.68,
        dc_similarity=0.73,
        lightgbm_score=0.71,
        shap_values={
            "carbon_intensity_g_kwh": 0.17,
            "dist_fiber_km": 0.11,
            "buildable_fraction": 0.09,
        },
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="851f2a6bfffffff",
        country_code="SE",
        region_name="Stockholm North",
        latitude=59.437,
        longitude=18.045,
        mean_price_eur_mwh=51,
        price_volatility=23,
        carbon_intensity_g_kwh=35,
        congestion_index=0.43,
        headroom_mw=260,
        dist_hv_substation_km=5.8,
        dist_fiber_km=4.9,
        dist_ixp_km=12,
        latency_proxy_ms=7.0,
        solar_cf=0.12,
        wind_cf=0.31,
        water_dist_km=1.4,
        cooling_degree_proxy=0.31,
        buildable_fraction=0.54,
        dc_similarity=0.77,
        lightgbm_score=0.75,
        shap_values={"dist_fiber_km": 0.2, "dc_similarity": 0.15, "congestion_index": -0.08},
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="851f204ffffffff",
        country_code="SE",
        region_name="Umea",
        latitude=63.8258,
        longitude=20.263,
        mean_price_eur_mwh=36,
        price_volatility=18,
        carbon_intensity_g_kwh=26,
        congestion_index=0.25,
        headroom_mw=450,
        dist_hv_substation_km=11.4,
        dist_fiber_km=20.1,
        dist_ixp_km=530,
        latency_proxy_ms=12.4,
        solar_cf=0.10,
        wind_cf=0.41,
        water_dist_km=4.2,
        cooling_degree_proxy=0.21,
        buildable_fraction=0.75,
        dc_similarity=0.76,
        lightgbm_score=0.74,
        shap_values={
            "headroom_mw": 0.2,
            "buildable_fraction": 0.12,
            "dist_hv_substation_km": -0.04,
        },
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="851fa62bfffffff",
        country_code="DE",
        region_name="Frankfurt West",
        latitude=50.1109,
        longitude=8.6821,
        mean_price_eur_mwh=86,
        price_volatility=34,
        carbon_intensity_g_kwh=348,
        congestion_index=0.82,
        headroom_mw=320,
        dist_hv_substation_km=3.3,
        dist_fiber_km=1.2,
        dist_ixp_km=2.0,
        latency_proxy_ms=1.1,
        solar_cf=0.12,
        wind_cf=0.25,
        water_dist_km=2.0,
        cooling_degree_proxy=0.62,
        buildable_fraction=0.46,
        dc_similarity=0.88,
        lightgbm_score=0.91,
        shap_values={"dist_fiber_km": 0.27, "dc_similarity": 0.23, "congestion_index": -0.18},
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="851f8d57fffffff",
        country_code="DE",
        region_name="Hamburg South",
        latitude=53.5511,
        longitude=9.9937,
        mean_price_eur_mwh=78,
        price_volatility=31,
        carbon_intensity_g_kwh=302,
        congestion_index=0.67,
        headroom_mw=240,
        dist_hv_substation_km=6.1,
        dist_fiber_km=5.0,
        dist_ixp_km=19,
        latency_proxy_ms=4.2,
        solar_cf=0.11,
        wind_cf=0.33,
        water_dist_km=1.8,
        cooling_degree_proxy=0.49,
        buildable_fraction=0.52,
        dc_similarity=0.72,
        lightgbm_score=0.68,
        shap_values={"dist_fiber_km": 0.13, "wind_cf": 0.08, "headroom_mw": -0.06},
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="851fa1cffffffff",
        country_code="DE",
        region_name="Munich North",
        latitude=48.1351,
        longitude=11.582,
        mean_price_eur_mwh=91,
        price_volatility=36,
        carbon_intensity_g_kwh=330,
        congestion_index=0.74,
        headroom_mw=210,
        dist_hv_substation_km=7.8,
        dist_fiber_km=7.5,
        dist_ixp_km=23,
        latency_proxy_ms=4.8,
        solar_cf=0.13,
        wind_cf=0.22,
        water_dist_km=5.1,
        cooling_degree_proxy=0.58,
        buildable_fraction=0.43,
        dc_similarity=0.66,
        lightgbm_score=0.62,
        shap_values={
            "dist_ixp_km": 0.08,
            "carbon_intensity_g_kwh": -0.13,
            "congestion_index": -0.09,
        },
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="85195da7fffffff",
        country_code="IE",
        region_name="Dublin West",
        latitude=53.3498,
        longitude=-6.2603,
        mean_price_eur_mwh=104,
        price_volatility=42,
        carbon_intensity_g_kwh=415,
        congestion_index=0.94,
        headroom_mw=140,
        dist_hv_substation_km=4.5,
        dist_fiber_km=2.1,
        dist_ixp_km=5,
        latency_proxy_ms=2.8,
        solar_cf=0.10,
        wind_cf=0.38,
        water_dist_km=1.2,
        cooling_degree_proxy=0.45,
        buildable_fraction=0.39,
        dc_similarity=0.86,
        lightgbm_score=0.89,
        shap_values={"dist_fiber_km": 0.2, "dc_similarity": 0.18, "congestion_index": -0.24},
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="85195c53fffffff",
        country_code="IE",
        region_name="Galway East",
        latitude=53.2707,
        longitude=-9.0568,
        mean_price_eur_mwh=98,
        price_volatility=39,
        carbon_intensity_g_kwh=390,
        congestion_index=0.61,
        headroom_mw=230,
        dist_hv_substation_km=14.2,
        dist_fiber_km=16.0,
        dist_ixp_km=190,
        latency_proxy_ms=6.1,
        solar_cf=0.09,
        wind_cf=0.44,
        water_dist_km=3.7,
        cooling_degree_proxy=0.38,
        buildable_fraction=0.58,
        dc_similarity=0.61,
        lightgbm_score=0.55,
        shap_values={"wind_cf": 0.12, "headroom_mw": -0.05, "dist_fiber_km": -0.04},
        exclusion_flag=False,
    ),
    SiteFeature(
        cell_id="85195c8ffffffff",
        country_code="IE",
        region_name="Cork North",
        latitude=51.8985,
        longitude=-8.4756,
        mean_price_eur_mwh=99,
        price_volatility=40,
        carbon_intensity_g_kwh=398,
        congestion_index=0.64,
        headroom_mw=260,
        dist_hv_substation_km=10.5,
        dist_fiber_km=11.6,
        dist_ixp_km=220,
        latency_proxy_ms=6.8,
        solar_cf=0.10,
        wind_cf=0.41,
        water_dist_km=2.4,
        cooling_degree_proxy=0.41,
        buildable_fraction=0.56,
        dc_similarity=0.63,
        lightgbm_score=0.58,
        shap_values={"wind_cf": 0.1, "buildable_fraction": 0.07, "carbon_intensity_g_kwh": -0.1},
        exclusion_flag=False,
    ),
]


def get_site(cell_id: str) -> SiteFeature | None:
    """Return one fixture site by H3 cell ID."""

    return next((site for site in FEATURE_COLLECTION if site.cell_id == cell_id), None)
