"""Europe-wide site dataset used by the API and the subset ingestion pipeline.

The dataset is generated by `scripts/build_europe_dataset.mjs` from curated
metros and public country-level reference values, then committed as
`data/europe_sites.json`. Loading it here keeps the `FEATURE_COLLECTION` /
`get_site` contract unchanged while letting the data scale to the whole
continent without a large hand-written Python literal. Regenerate the JSON
(and the static map layers) after changing the generator.
"""

from __future__ import annotations

import json
from functools import lru_cache
from pathlib import Path
from typing import cast

from backend.engine.contracts import SiteFeature

_DATASET_PATH = Path(__file__).resolve().parent / "data" / "europe_sites.json"


@lru_cache(maxsize=1)
def _load_collection() -> tuple[SiteFeature, ...]:
    """Parse and validate the committed dataset once per process."""

    raw = json.loads(_DATASET_PATH.read_text(encoding="utf-8"))
    if not isinstance(raw, list):
        raise ValueError(f"Expected a JSON array of sites in {_DATASET_PATH}.")
    records = cast("list[object]", raw)
    return tuple(SiteFeature.model_validate(record) for record in records)


# Module-level collection so existing imports (`from ... import FEATURE_COLLECTION`)
# keep working. It is a tuple to signal read-only, deterministic data.
FEATURE_COLLECTION: tuple[SiteFeature, ...] = _load_collection()


def get_site(cell_id: str) -> SiteFeature | None:
    """Return one dataset site by H3 cell ID."""

    return next((site for site in FEATURE_COLLECTION if site.cell_id == cell_id), None)
