import { API_BASE_URL } from "../config/env";
import type { LayerResponse } from "../types/api";
import { requestJson } from "./client";

/**
 * Fetch a map-layer GeoJSON.
 *
 * The SPA prefers the pre-computed static asset under
 * `frontend/public/layers/{name}.json` (CDN-cacheable, generated by
 * `make layer-assets`). On any failure or 404, falls back to the live
 * `/layers/{name}` API endpoint, which is always authoritative.
 */
export async function getLayer(layerName: string): Promise<LayerResponse> {
  const staticUrl = `${API_BASE_URL}/layers/${layerName}.json`;
  try {
    const response = await fetch(staticUrl, {
      // Long max-age is fine: a regenerated overlay produces a new file.
      headers: { Accept: "application/json" },
    });
    if (response.ok) {
      return (await response.json()) as LayerResponse;
    }
  } catch {
    // Fall through to the live API.
  }
  return requestJson<LayerResponse>(`/layers/${layerName}`);
}
