/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/agent/explain": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Explain
         * @description Explain a selected site for the chat panel; falls back to a template.
         */
        post: operations["explain_agent_explain_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/assumptions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Assumptions
         * @description Return the public assumptions used by the fixture skeleton.
         */
        get: operations["assumptions_assumptions_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health
         * @description Return process health, version metadata, and dependency status.
         */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/layers/{layer_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Layer
         * @description Return a GeoJSON layer for the requested fixture feature.
         */
        get: operations["layer_layers__layer_name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/meta/source-artifacts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Source Artifacts
         * @description Operational metadata for source versions and ingestion artifacts.
         */
        get: operations["source_artifacts_meta_source_artifacts_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/optimize/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Optimizer Job Status
         * @description Return the persisted state for a previously enqueued job.
         */
        get: operations["optimizer_job_status_optimize_jobs__job_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/optimize/supply-mix": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize
         * @description Return a chart-ready single-site supply-mix optimization response.
         */
        post: operations["optimize_optimize_supply_mix_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/optimize/supply-mix/async": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Optimize Async
         * @description Schedule the LP solve in the background and return the job id immediately.
         */
        post: operations["optimize_async_optimize_supply_mix_async_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/compare": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Compare
         * @description Compare selected fixture site cells.
         */
        post: operations["compare_sites_compare_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Search
         * @description Rank fixture sites for a requested load size.
         */
        post: operations["search_sites_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sites/{cell_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Site Detail
         * @description Return full fixture details for a single site cell.
         */
        get: operations["site_detail_sites__cell_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ApiErrorDetail */
        ApiErrorDetail: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ApiErrorResponse */
        ApiErrorResponse: {
            detail: components["schemas"]["ApiErrorDetail"];
        };
        /** AssumptionsResponse */
        AssumptionsResponse: {
            /** Assumptions */
            assumptions: {
                [key: string]: unknown;
            };
            /** Cache Key */
            cache_key: string;
            /** Data Mode */
            data_mode: string;
        };
        /** CompareRequest */
        CompareRequest: {
            /** Cell Ids */
            cell_ids: string[];
        };
        /** CompareResponse */
        CompareResponse: {
            /**
             * Cache Key
             * @default
             */
            cache_key: string;
            /**
             * Data Mode
             * @default fixture
             * @constant
             */
            data_mode: "fixture";
            /** Sites */
            sites: components["schemas"]["SiteFeature"][];
        };
        /**
         * ExplainRequest
         * @description Payload for `POST /agent/explain`.
         */
        ExplainRequest: {
            /** Cell Id */
            cell_id: string;
            /** Power Mw */
            power_mw: number;
            /**
             * Workload Type
             * @default training
             * @enum {string}
             */
            workload_type: "training" | "inference" | "mixed";
        };
        /**
         * ExplainResponse
         * @description Result of an agent explanation. Falls back to the template on any LLM error.
         *
         *     `source` lets the UI render a "Live · gpt-4o-mini" pill versus a
         *     "Deterministic template" pill; both render the same chat bubble shape.
         */
        ExplainResponse: {
            /** Cache Key */
            cache_key: string;
            /** Cell Id */
            cell_id: string;
            /** Message */
            message: string;
            /** Model */
            model?: string | null;
            /**
             * Source
             * @enum {string}
             */
            source: "openai" | "template";
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * HealthDependencies
         * @description Aggregate dependency status surfaced from `/health`.
         */
        HealthDependencies: {
            postgres: components["schemas"]["HealthDependency"];
            redis: components["schemas"]["HealthDependency"];
        };
        /**
         * HealthDependency
         * @description Status of one dependency the API talks to (Postgres, Redis, ...).
         */
        HealthDependency: {
            /** Detail */
            detail?: string | null;
            /** Latency Ms */
            latency_ms?: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "unreachable" | "disabled";
        };
        /** HealthResponse */
        HealthResponse: {
            /** Cache Key */
            cache_key: string;
            /** Data Mode */
            data_mode: string;
            dependencies?: components["schemas"]["HealthDependencies"] | null;
            /** Git Sha */
            git_sha?: string | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
            /**
             * Uptime Seconds
             * @default 0
             */
            uptime_seconds: number;
            /**
             * Version
             * @default 0.0.0
             */
            version: string;
        };
        /** LayerFeature */
        LayerFeature: {
            geometry: components["schemas"]["PointGeometry"];
            properties: components["schemas"]["LayerFeatureProperties"];
            /**
             * Type
             * @default Feature
             * @constant
             */
            type: "Feature";
        };
        /** LayerFeatureProperties */
        LayerFeatureProperties: {
            /** Buildable Fraction */
            buildable_fraction: number;
            /** Carbon Intensity G Kwh */
            carbon_intensity_g_kwh: number;
            /** Cell Id */
            cell_id: string;
            /** Congestion Index */
            congestion_index: number;
            /** Cooling Degree Proxy */
            cooling_degree_proxy: number;
            /** Country Code */
            country_code: string;
            /** Dc Similarity */
            dc_similarity: number;
            /** Dist Fiber Km */
            dist_fiber_km: number;
            /** Dist Hv Substation Km */
            dist_hv_substation_km: number;
            /** Dist Ixp Km */
            dist_ixp_km: number;
            /** Exclusion Flag */
            exclusion_flag: boolean;
            /** Headroom Mw */
            headroom_mw: number;
            /** Latency Proxy Ms */
            latency_proxy_ms: number;
            /** Latitude */
            latitude: number;
            /** Layer Name */
            layer_name: string;
            /** Layer Value */
            layer_value: number;
            /** Lightgbm Score */
            lightgbm_score: number;
            /** Longitude */
            longitude: number;
            /** Mean Price Eur Mwh */
            mean_price_eur_mwh: number;
            /** Price Volatility */
            price_volatility: number;
            /** Region Name */
            region_name: string;
            /**
             * Resolution
             * @default 5
             */
            resolution: number;
            /** Shap Values */
            shap_values: {
                [key: string]: number;
            };
            /** Solar Cf */
            solar_cf: number;
            /** Water Dist Km */
            water_dist_km: number;
            /** Wind Cf */
            wind_cf: number;
        };
        /** LayerResponse */
        LayerResponse: {
            /**
             * Cache Key
             * @default
             */
            cache_key: string;
            /** Features */
            features: components["schemas"]["LayerFeature"][];
            /**
             * Type
             * @default FeatureCollection
             * @constant
             */
            type: "FeatureCollection";
        };
        /**
         * OptimizationJobAccepted
         * @description Returned with HTTP 202 from `POST /optimize/supply-mix/async`.
         */
        OptimizationJobAccepted: {
            /** Cache Key */
            cache_key: string;
            /** Job Id */
            job_id: string;
            /**
             * Status
             * @default pending
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
            /** Status Url */
            status_url: string;
        };
        /**
         * OptimizationJobStatus
         * @description Polled via `GET /optimize/jobs/{job_id}`. Mirrors `optimization_runs`.
         */
        OptimizationJobStatus: {
            /** Cache Key */
            cache_key: string;
            /** Completed At */
            completed_at?: string | null;
            error?: components["schemas"]["ApiErrorDetail"] | null;
            /** Job Id */
            job_id: string;
            /** Request Id */
            request_id?: string | null;
            result?: components["schemas"]["SupplyMixResponse"] | null;
            /** Solve Ms */
            solve_ms?: number | null;
            /** Started At */
            started_at?: string | null;
            /**
             * Status
             * @enum {string}
             */
            status: "pending" | "running" | "completed" | "failed";
        };
        /** OptimizeRequest */
        OptimizeRequest: {
            /** Carbon Cap G Kwh */
            carbon_cap_g_kwh?: number | null;
            /** Cell Id */
            cell_id: string;
            /** Load Mw */
            load_mw: number;
            /**
             * Load Profile
             * @default flat_24_7
             * @enum {string}
             */
            load_profile: "flat_24_7" | "spiky_training";
        };
        /** ParetoPoint */
        ParetoPoint: {
            /** Backup Share */
            backup_share: number;
            /** Battery Shifted Share */
            battery_shifted_share: number;
            /** Carbon Cap G Kwh */
            carbon_cap_g_kwh: number | null;
            /** Curtailment Share */
            curtailment_share: number;
            /** Effective Carbon G Kwh */
            effective_carbon_g_kwh: number;
            /** Effective Cost Eur Mwh */
            effective_cost_eur_mwh: number;
            /** Grid Share */
            grid_share: number;
            /** Onsite Solar Share */
            onsite_solar_share: number;
            /** Solar Ppa Share */
            solar_ppa_share: number;
            /** Wind Ppa Share */
            wind_ppa_share: number;
        };
        /** PointGeometry */
        PointGeometry: {
            /** Coordinates */
            coordinates: [
                number,
                number
            ];
            /**
             * Type
             * @default Point
             * @constant
             */
            type: "Point";
        };
        /** RankedSite */
        RankedSite: {
            /** Composite Score */
            composite_score: number;
            /** Score Breakdown */
            score_breakdown: {
                [key: string]: number;
            };
            /** Score Contributions */
            score_contributions: {
                [key: string]: number;
            };
            /** Score Explanations */
            score_explanations: components["schemas"]["ScoreExplanation"][];
            site: components["schemas"]["SiteFeature"];
        };
        /** ScaleWarning */
        ScaleWarning: {
            /** Code */
            code: string;
            /** Message */
            message: string;
        };
        /** ScoreExplanation */
        ScoreExplanation: {
            /** Contribution */
            contribution: number;
            /**
             * Direction
             * @enum {string}
             */
            direction: "lower_is_better" | "higher_is_better" | "composite";
            /** Factor */
            factor: string;
            /** Raw Value */
            raw_value: string;
            /** Score */
            score: number;
            /** Weight */
            weight: number;
        };
        /** SearchRequest */
        SearchRequest: {
            /** Country Filter */
            country_filter?: string[] | null;
            /** Power Mw */
            power_mw: number;
            /**
             * Top K
             * @default 10
             */
            top_k: number;
            weights?: components["schemas"]["Weights"];
            /**
             * Workload Type
             * @default training
             * @enum {string}
             */
            workload_type: "training" | "inference" | "mixed";
        };
        /** SearchResponse */
        SearchResponse: {
            /**
             * Cache Key
             * @default
             */
            cache_key: string;
            /**
             * Data Mode
             * @default fixture
             * @constant
             */
            data_mode: "fixture";
            /** Requested Power Mw */
            requested_power_mw: number;
            /** Results */
            results: components["schemas"]["RankedSite"][];
            /** Warnings */
            warnings: components["schemas"]["ScaleWarning"][];
            /** Workload Type */
            workload_type: string;
        };
        /** SiteDetailResponse */
        SiteDetailResponse: {
            /**
             * Cache Key
             * @default
             */
            cache_key: string;
            /**
             * Data Mode
             * @default fixture
             * @constant
             */
            data_mode: "fixture";
            site: components["schemas"]["SiteFeature"];
        };
        /** SiteFeature */
        SiteFeature: {
            /** Buildable Fraction */
            buildable_fraction: number;
            /** Carbon Intensity G Kwh */
            carbon_intensity_g_kwh: number;
            /** Cell Id */
            cell_id: string;
            /** Congestion Index */
            congestion_index: number;
            /** Cooling Degree Proxy */
            cooling_degree_proxy: number;
            /** Country Code */
            country_code: string;
            /** Dc Similarity */
            dc_similarity: number;
            /** Dist Fiber Km */
            dist_fiber_km: number;
            /** Dist Hv Substation Km */
            dist_hv_substation_km: number;
            /** Dist Ixp Km */
            dist_ixp_km: number;
            /** Exclusion Flag */
            exclusion_flag: boolean;
            /** Headroom Mw */
            headroom_mw: number;
            /** Latency Proxy Ms */
            latency_proxy_ms: number;
            /** Latitude */
            latitude: number;
            /** Lightgbm Score */
            lightgbm_score: number;
            /** Longitude */
            longitude: number;
            /** Mean Price Eur Mwh */
            mean_price_eur_mwh: number;
            /** Price Volatility */
            price_volatility: number;
            /** Region Name */
            region_name: string;
            /**
             * Resolution
             * @default 5
             */
            resolution: number;
            /** Shap Values */
            shap_values: {
                [key: string]: number;
            };
            /** Solar Cf */
            solar_cf: number;
            /** Water Dist Km */
            water_dist_km: number;
            /** Wind Cf */
            wind_cf: number;
        };
        /**
         * SourceArtifact
         * @description One row from `source_artifacts.db` exposed via `/meta/source-artifacts`.
         */
        SourceArtifact: {
            /** Artifact Name */
            artifact_name: string;
            /** Artifact Path */
            artifact_path: string;
            /** Artifact Version */
            artifact_version: string;
            /** Checksum Sha256 */
            checksum_sha256: string;
            /** Country Scope */
            country_scope: string;
            /** Fallback */
            fallback?: string | null;
            /** Generated At */
            generated_at: string;
            /** Metadata */
            metadata?: {
                [key: string]: unknown;
            };
            /** Record Count */
            record_count: number;
            /** Source Name */
            source_name: string;
            /** Source Status */
            source_status: string;
            /** Status */
            status: string;
        };
        /**
         * SourceArtifactsResponse
         * @description Operational metadata for the active data slice.
         *
         *     `data_version` is a stable short fingerprint over the artifact checksums;
         *     consumers can use it to detect when ingestion has produced a new slice.
         */
        SourceArtifactsResponse: {
            /** Artifact Count */
            artifact_count: number;
            /** Artifacts */
            artifacts: components["schemas"]["SourceArtifact"][];
            /** Cache Key */
            cache_key: string;
            /** Data Mode */
            data_mode: string;
            /** Data Version */
            data_version: string;
        };
        /** SupplyMixResponse */
        SupplyMixResponse: {
            /** Annual Matched Clean Share */
            annual_matched_clean_share: number;
            /**
             * Cache Key
             * @default
             */
            cache_key: string;
            /** Cell Id */
            cell_id: string;
            /**
             * Data Mode
             * @default fixture
             * @constant
             */
            data_mode: "fixture";
            /** Dispatch Preview */
            dispatch_preview: {
                [key: string]: number;
            }[];
            /** Dispatch Summary */
            dispatch_summary: {
                [key: string]: number;
            };
            /** Effective Carbon G Kwh */
            effective_carbon_g_kwh: number;
            /** Effective Cost Eur Mwh */
            effective_cost_eur_mwh: number;
            /** Hourly 24 7 Cfe Share */
            hourly_24_7_cfe_share: number;
            /** Load Mw */
            load_mw: number;
            /** Load Profile */
            load_profile: string;
            /** Optimization Horizon Hours */
            optimization_horizon_hours: number;
            /** Pareto Frontier */
            pareto_frontier: components["schemas"]["ParetoPoint"][];
            /** Recommended Portfolio */
            recommended_portfolio: {
                [key: string]: number;
            };
            /** Solver Status */
            solver_status: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
        /** Weights */
        Weights: {
            /**
             * Carbon
             * @default 0.24
             */
            carbon: number;
            /**
             * Congestion
             * @default 0.18
             */
            congestion: number;
            /**
             * Connectivity
             * @default 0.1
             */
            connectivity: number;
            /**
             * Grid
             * @default 0.14
             */
            grid: number;
            /**
             * Land
             * @default 0.08
             */
            land: number;
            /**
             * Ml
             * @default 0.08
             */
            ml: number;
            /**
             * Price
             * @default 0.18
             */
            price: number;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    explain_agent_explain_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ExplainRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ExplainResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    assumptions_assumptions_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AssumptionsResponse"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
    layer_layers__layer_name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LayerResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    source_artifacts_meta_source_artifacts_get: {
        parameters: {
            query?: {
                /** @description Exact artifact name match. */
                artifact_name?: string | null;
                /** @description ISO-3166 alpha-2 country code; matches scoped or comma-separated lists. */
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceArtifactsResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimizer_job_status_optimize_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobStatus"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    optimize_optimize_supply_mix_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SupplyMixResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Unprocessable Content */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
        };
    };
    optimize_async_optimize_supply_mix_async_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OptimizeRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["OptimizationJobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    compare_sites_compare_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CompareRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompareResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    search_sites_search_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    site_detail_sites__cell_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                cell_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SiteDetailResponse"];
                };
            };
            /** @description Not Found */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiErrorResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
